### ISSUE TITLE
Are you sure this webview blocks ads.?

### ISSUE THREAD

**Issue by rubinnellikunnathu** [AmniX/AdBlockedWebView-Android#1]
I just tried ur demo and im still getting ads.

![device-2016-11-30-142442](https://cloud.githubusercontent.com/assets/13848574/20745867/33adfca6-b709-11e6-8664-2747502d93fe.png)
![device-2016-11-30-142541](https://cloud.githubusercontent.com/assets/13848574/20745869/33e2d9ee-b709-11e6-81ae-14fd00a56d2c.png)
![device-2016-11-30-142614](https://cloud.githubusercontent.com/assets/13848574/20745868/33e2990c-b709-11e6-8ad7-1f70e17c9593.png)

**Comment by AmniX** [comment]
Popup Ads are not blocked yet but it can be Later, also if you are still able to see banner Ads then capture the URL, Eject the Host name and add it to hosts file which is located in assets folder of library. 

Good day!
